version: '1'
services:
  postgres:
    image: "postgres:15"
    restart: on-failure
    ports:
      - '5432:5432'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
